import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Header from "@/components/Header/Header";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body>
        <Header />
        <nav className="flex gap-5 justify-center mt-5 text-xl">
          <Link href="/">Accueil</Link>
          <Link href="/blog">Blog</Link>
          <Link href="/blog/bonsoir">Article</Link>
          <Link href="/about">A Propos</Link>
          <Link href="/create">Créer</Link>
        </nav>
        <main className="text-center mt-16">
          {children}

          <ToastContainer position="bottom-right" />
        </main>
      </body>
    </html>
  );
}
